config/routes.rb
Rails.application.routes.draw do
  root 'creators#index'
  
  resources :creators, only: [:new, :create, :update, :destroy, :edit, :show] do
    resources :tiers, only: [:new, :index, :edit]
    resources :pledges, only: [:new, :index]
  end

  resources :users, only: [:new, :create, :update, :destroy, :edit, :show] do
    resources :pledges, only: [:index]
  end

  resources :tiers, only: [:create, :update, :destroy]
  resources :pledges, only: [:create, :update, :destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'callbacks#google'
  get '/auth/failure', to: redirect('/')

  get '/tiers/most_expensive_9', to: 'tiers#show'

end

app/models/user.rb
class User < SuperUser
    has_many :pledges
    has_many :creators, through: :pledges


    def pledge_amount(creator)
        self.pledges.select { |p| p.creator_id == creator.id }.first.amount
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :clean_params, only: [:create, :update]


    def show
        @user = User.find_by_id(params[:id])
        redirect_if_not_owner(@user)
    end

    def new
        if logged_in?
            redirect_to root_path
        end
        @user = User.new
    end

    def create
        if !Creator.find_by(email: params[:user][:email]) 
            @user = User.new(user_params)
            if @user.save
                set_session(@user)
                redirect_to user_pledges_path(@user)
            else
                render 'new'
            end
        else
            render 'new'
        end
    end

    def edit
        @user = User.find_by_id(params[:id])
        redirect_if_not_owner(@user)
    end

    def update
        if !Creator.find_by(email: params[:user][:email])
            @user = User.find_by_id(params[:id])
            if @user.update(user_params)
                redirect_to user_pledges_path(@user)
            end
        else
            render 'edit'
        end
    end

    def destroy
        @user = User.find_by_id(params[:id])
        redirect_if_not_owner(@user)
        reset_session
        @user.pledges.destroy_all
        @user.destroy
        redirect_to '/'
    end

    private

    def user_params

        params.require(:user).permit(:email, :name, :privacy, :password, :password_confirmation)
    end

    def clean_params
        params[:user][:name].titleize
        params[:user][:email].downcase
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.erb
<% if @user.errors.any? %>
    <ul>
        <% @user.errors.messages.each do |msg| %>
            <li class="alert-box"><%= display_errors(msg) %></li>
        <% end %>
    </ul>
<% end %>

app/views/users/edit.erb
<h1>Edit Account</h1>

<%= render 'errors' %>

<%= form_with model: @user, local: true do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name, autocomplete: "name", required: true, class: "field-space" %>
    </div>
    <div>
        <%= f.label :email %>
        <%= f.email_field :email, autocomplete: "email", required: true, class: "field-space" %>
    </div>
    <div>
        <%= f.label :privacy, "Would you like your support to be private?" %>
        <%= f.check_box :privacy, class: "field-space" %>
    </div>

    <%= f.submit class: "button" %>
<% end %>

app/views/users/new.erb
<div class="signup-header">
    <h1 class="title-header">New User Signup</h1>
    <%= link_to "Creator Signup Here", new_creator_path, class: "button" %>
</div>

<%= render 'errors' %>

<%= form_with model: @user, local: true do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, autocomplete: "name", required: true, class: "field-space" %><br>
    <%= f.label :email %>
    <%= f.email_field :email, autocomplete: "email", required: true, class: "field-space" %><br>
    <%= f.label :privacy, "Would you like your support to be private?" %>
    <%= f.check_box :privacy %><br>
    <%= f.label :password %>
    <%= f.password_field :password, required: true, class: "field-space" %><br>
    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation, required: true, class: "field-space" %><br>

    <%= f.submit class: "button" %>
<% end %>

<%= button_to 'Signup with Google', '/auth/google_oauth2', class: "button" %><br>

app/views/users/show.erb
<div class="center">
    <h2>Hi, <%= @user.name %></h2>
    <%= @user.email %><br>
    <h3><%= link_to "Edit Account", edit_user_path(@user) %> || 
    <%= link_to "Delete Account", user_path(@user), data: { confirm: "Are you sure?" }, method: :delete %></h3>
</div>

<div class="center">
    <h1>Currently Supporting</h1>
</div>

<div class="display-box">
    <% @user.pledges.each do |pledge| %>
        <div class="creator-box">
            <%= link_to pledge.creator.name, creator_path(pledge.creator), class: "button" %>
            <div class="field-space">$<%= pledge.amount.to_i %> per month</div>
            <p class="field-space"><%= pledge.to_tier.description %></p>
            <%= link_to "Delete", pledge_path(pledge), data: { confirm: "Are you sure?" }, method: :delete, class: "norm-link bottom" %>
        </div>
    <% end %>
</div>