config/routes.rb
Rails.application.routes.draw do
  root 'creators#index'
  
  resources :creators, only: [:new, :create, :update, :destroy, :edit, :show] do
    resources :tiers, only: [:new, :index, :edit]
    resources :pledges, only: [:new, :index]
  end

  resources :users, only: [:new, :create, :update, :destroy, :edit, :show] do
    resources :pledges, only: [:index]
  end

  resources :tiers, only: [:create, :update, :destroy]
  resources :pledges, only: [:create, :update, :destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'callbacks#google'
  get '/auth/failure', to: redirect('/')

  get '/tiers/most_expensive_9', to: 'tiers#show'

end

app/models/creator.rb
class Creator < SuperUser
    has_many :tiers
    has_many :pledges
    has_many :users, through: :pledges
    scope :state, ->(state) { where("state == ?", state ) }
    validates :about, length: { maximum: 500 }
    scope :random_creator, -> { order(Arel.sql('RANDOM()')).first }
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
    before_action :clean_params, only: [:create, :update]
    
    def index
        if params[:search].blank?
            @creators = Creator.all
        else
            @creators = Creator.state(params[:search])
        end
    end

    def new
        @creator = Creator.new
    end

    def create
        if !User.find_by(email: params[:creator][:email])
            @creator = Creator.new(creator_params)
            if @creator.save
                set_session(@creator)
                redirect_to creator_path(@creator)
            else
                render 'new'
            end
        else
            render 'new'
        end
    end

    def show
        @creator = Creator.find_by_id(params[:id])
        @tiers = @creator.tiers.order(:amount)
        @pledges = @creator.pledges     
    end

    def edit
        @creator = Creator.find_by_id(params[:id])
        redirect_if_not_owner(@creator)
    end

    def update
        if !User.find_by(email: params[:creator][:email])
            @creator = Creator.find_by_id(params[:id])
            if @creator.update(creator_params)
                redirect_to creator_path(@creator)
            end
        else
            render 'edit'
        end
    end

    def destroy
        @creator = Creator.find_by_id(params[:id])
        redirect_if_not_owner(@creator)
        reset_session
        @creator.destroy
        redirect_to '/'
    end

    private

    def creator_params
        params.require(:creator).permit(:email, :name, :about, :password, :password_confirmation, :state, :profile_pic)
    end

    def clean_params
        params[:creator][:name].titleize
        params[:creator][:email].downcase
    end
end

app/helpers/creators_helper.rb
module CreatorsHelper

    def all_states
        states = Array[ ["AK", "Alaska"], 
                ["AL", "Alabama"], 
                ["AR", "Arkansas"], 
                ["AS", "American Samoa"], 
                ["AZ", "Arizona"], 
                ["CA", "California"], 
                ["CO", "Colorado"], 
                ["CT", "Connecticut"], 
                ["DC", "District of Columbia"], 
                ["DE", "Delaware"], 
                ["FL", "Florida"], 
                ["GA", "Georgia"], 
                ["GU", "Guam"], 
                ["HI", "Hawaii"], 
                ["IA", "Iowa"], 
                ["ID", "Idaho"], 
                ["IL", "Illinois"], 
                ["IN", "Indiana"], 
                ["KS", "Kansas"], 
                ["KY", "Kentucky"], 
                ["LA", "Louisiana"], 
                ["MA", "Massachusetts"], 
                ["MD", "Maryland"], 
                ["ME", "Maine"], 
                ["MI", "Michigan"], 
                ["MN", "Minnesota"], 
                ["MO", "Missouri"], 
                ["MS", "Mississippi"], 
                ["MT", "Montana"], 
                ["NC", "North Carolina"], 
                ["ND", "North Dakota"], 
                ["NE", "Nebraska"], 
                ["NH", "New Hampshire"], 
                ["NJ", "New Jersey"], 
                ["NM", "New Mexico"], 
                ["NV", "Nevada"], 
                ["NY", "New York"], 
                ["OH", "Ohio"], 
                ["OK", "Oklahoma"], 
                ["OR", "Oregon"], 
                ["PA", "Pennsylvania"], 
                ["PR", "Puerto Rico"], 
                ["RI", "Rhode Island"], 
                ["SC", "South Carolina"], 
                ["SD", "South Dakota"], 
                ["TN", "Tennessee"], 
                ["TX", "Texas"], 
                ["UT", "Utah"], 
                ["VA", "Virginia"], 
                ["VI", "Virgin Islands"], 
                ["VT", "Vermont"], 
                ["WA", "Washington"], 
                ["WI", "Wisconsin"], 
                ["WV", "West Virginia"], 
                ["WY", "Wyoming"] ]
    end

    def creator_pic(creator)
        if creator.profile_pic.blank?
            image_tag('default-pic.png', id: "mic-img")
        else
            image_tag(creator.profile_pic, id: "mic-img")
        end
    end
end

app/views/creators/_errors.erb
<% if @creator.errors.any? %>
    <ul>
        <% @creator.errors.messages.each do |msg| %>
            <li class="alert-box"><%= display_errors(msg) %></li>
        <% end %>
    </ul>
<% end %>

app/views/creators/edit.erb
<h1 class="center">Edit a Creator</h1>

<%= render 'errors' %>

<%= form_with model: @creator, local: true do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, autocomplete: "name", required: true, class: "field-space" %><br>
    <%= f.label :email %>
    <%= f.email_field :email, autocomplete: "email", required: true, class: "field-space" %><br>
    <%= f.label :state %>
    <%= f.collection_select :state, all_states, :second, :second, class: "field-space" %><br>
    <%= f.label :profile_pic, "Profile Picture URL" %>
    <%= f.text_field :profile_pic, class: "field-space" %><br>
    <%= f.label :about, class: "desc-label" %>
    <%= f.text_area :about, required: true, rows: 10, cols: 40, class: "field-space" %>

    <%= f.submit class: "button" %>
<% end %>

app/views/creators/index.erb
<h1 class="center separation-line">Welcome to Faketreon</h1>

<div id="home-container">
    <div id="home-descriptor">
        <p class="center">We are a platform built for creators, by creators. 
        We allow makers of all kinds to share their work with their audience and 
        provide a means to be supported financially by the fans themselves.</p>
        <p class="center">Connect with your favorite artists, podcasters, and makers
        in a dynamic way and stay up to date by getting rewards for support.</p>
    </div>
    <div class="image-cropper">
        <%= image_tag('microphone.jpg', id: "mic-img") %>
    </div>
</div>

<h4>Filter by State: 
    <%= form_tag(root_path, method: :get) do %>
        <%= select_tag :search, options_from_collection_for_select(all_states, :second, :second) %>
        <%= submit_tag ("Filter") %>
    <% end %>
</h4>

<% if @creators.blank? %>
    <h4>Sorry, no creators to display</h4>
<% end %>

<div class="display-box">
<% @creators.each do |creator| %>
    <div class="creator-box">
        <div class="button-div"><%= link_to creator.name, creator_path(creator), class: "button" %></div>
        <div class="state-name-container bold"><%= creator.state %></div>
        <div class="creator-about-container"><%= creator.about %></div>
        <div class="pledges-container"><%= creator.pledges.count %> Patrons</div>
    </div>
<% end %>
</div>

app/views/creators/new.erb
<div class="signup-header">
    <h1 class="title-header">New Creator Signup</h1>
    <%= link_to "User Signup Here", new_user_path, class: "button" %>
</div>

<%= render 'errors' %>

<%= form_with model: @creator, local: true do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, autocomplete: "name", required: true, class: "field-space" %><br>
    <%= f.label :email %>
    <%= f.email_field :email, autocomplete: "email", required: true, class: "field-space" %><br>
    <%= f.label :state %>
    <%= f.collection_select :state, all_states, :second, :second, class: "field-space" %><br>
    <%= f.label :about, class: "desc-label" %>
    <%= f.text_area :about, required: true, rows: 10, cols: 40, class: "field-space" %><br>
    <%= f.label :profile_pic, "Profile Picture URL" %>
    <%= f.text_field :profile_pic, class: "field-space" %><br>
    <%= f.label :password %>
    <%= f.password_field :password, required: true, class: "field-space" %><br>
    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation, required: true, class: "field-space" %><br>

<%= f.submit class: "button" %>
<% end %>

<%#= button_to 'Signup with Google', '/auth/google_oauth2', class: "button" %>

app/views/creators/show.erb
<div>
    <div class="center slim">
        <div class="image-cropper">
            <%= creator_pic(@creator) %>
        </div>
        <h3><%= @creator.name %></h3>
        <p width="50%"><%= @creator.about %></p>
    </div>
    <div class="center">
    <% if current_user == @creator %>
        <div class="field-space">
            <%= link_to "Edit Profile", edit_creator_path(@creator), class: "norm-link" %> || 
            <%= link_to "Delete Profile", creator_path(@creator), data: { :confirm => 'Are you sure?' }, method: :delete, class: "norm-link" %><br><br>
        </div>
        <span class="non-button field-space center">New Post</span>
        <%= link_to "New Tier", new_creator_tier_path(@creator), class: "button center" %>
        </div>
        <div class="center">
            <h1>Your Current Membership Levels</h1>
    <% else %>
        <h1>Select a Membership Level</h1>
    <% end %>
    </div>

    <div class="display-box">
    <% @tiers.each do |tier| %>
        <div class="creator-box">
            <div class="title-heading"><%= tier.title %></div>
            <strong>$<%= tier.amount %> per month</strong>
            <div class="field-space"><%= tier.description %></div>
            <div class="bottom">
                <%= tier_button(tier) %>
            </div>
        </div>
    <% end %>
    </div>

    <div class="center">
        <h1 class="center"><%= @pledges.count %> Patrons</h1>
    </div>
    <ul class="pledge-box">
        <% if @pledges.any? %>
            <% @pledges.each do |pledge| %>
                <li class="pledge">
                    <div class="pledge-amount">$<%= pledge.amount.to_i %></div>
                    <%= (pledge.user.privacy ? " Anonymous" : pledge.user.name) %>
                </li>
            <% end %>
        <% end %>
    </ul>
</div>